### ISSUE TITLE
tests are confusing

### ISSUE THREAD

**Issue by duck2** [javier-lopez/genpass#18]
Well, after observing `./genpass` won't work in the main directory(#17), I wondered how are the tests passing in Travis.

At a first glance to [test.sh](https://github.com/chilicuil/genpass/blob/master/test/test.sh), things are not really obvious, turns out the actual tests are in [test.db](https://github.com/chilicuil/genpass/blob/master/test/test.db), and there are a bunch of `expect` tests in the other scripts in tests directory which are called via test.db.

When I run `sh test.sh`, my `getpass` tests were hanging. I thought it is my antique computer being slow but `cat tmp.dir/run.log | tail -n 20` has the output

```
+ test X1 = X1
+ getpass -h
+ head -1
sh: printf: I/O error
sh: printf: I/O error
sh: printf: I/O error
sh: printf: I/O error
sh: printf: I/O error
sh: printf: I/O error
sh: printf: I/O error
sh: printf: I/O error
sh: printf: I/O error
sh: printf: I/O error
sh: printf: I/O error
sh: printf: I/O error
sh: printf: I/O error
sh: printf: I/O error
sh: printf: I/O error
sh: printf: I/O error
Site:
```

which shows it does not take input anyway. Running `xvfb-run sh test.sh` works- tests/README.md would need an update.

Furthermore, there is the line `cp ../../genpass-static ../../genpass` before the `getpass` tests in test.db, also all expect tests are `spawn`ing `genpass-static` which shows the actual genpass binary is never being tested. Removing that line results in the `getpass` test failing with the error mentioned in #17.

**Comment by javier-lopez** [comment]
Indeed, the tests could use some documentation :smiley:, and yes I'm just testing `genpass-static` because it bundles everything which is included on this project, other errors wouldn't be genpass fault, IMO.

The simple `sh tests.sh` fails because `getpass` requires a X server, the [test/README.md](https://github.com/chilicuil/genpass/blob/master/test/README.md) file has been [updated](https://github.com/chilicuil/genpass/commit/ef8c076070bf7375117ee70b45cdfcef21c82393) to reflect it :+1: 

Finally the `cp ../../genpass-static ../../genpass` is there because `getpass` calls `genpass` and it was easier this way to modify `getpass` on runtime.

If you have further ideas to improve the tests I'll happy to read them.

**Comment by duck2** [comment]
I am not really experienced in testing console programs- but if we are using `expect`, why not use it for all tests? That would remove all the `grep`, `sed` and `awk` playing in `test.sh` and `tmp.dir` and `run*` stuff.

The thing with `cp` is both `genpass`es are becoming `genpass-static` after running the tests, which is unexpected behaviour. I am for testing both binaries, but if we are testing just `genpass-static`, at least it could backup the dynamically linked binary.

edit: After thinking for a while, using expect is overkill for, say, testing something like `genpass -V` and expecting a return value of 0. However, we can reduce some of `test.db`'s opaqueness by removing `@begin` and `@end` parsing and dividing the tests between files as `genpass.db` and `getpass.db`.

edit2: On a second(third) thought, `make` looks more suitable for the purpose.

**Comment by javier-lopez** [comment]
As you already pointed out, `expect` can be overkill for simple tests so in such scenarios I use the `grep|sed|awk` combination to define multiple tests in a short space, one per line. I don't know enough `make` to do the conversion but if you do, I could use some help. If you do, please ensure it doesn't depend on an specific make implementation.

I think the genpass.db getpass.db separation is a good idea, the @begin/@end looks superficial on this case because it's just separating tests by binaries, however it could be used to define named tests who can help to tests by category.., kind of

Testing genpass ...
Input, help messages .... ok
Base64 password generation ... ok
Interactive password generation ... ok
...
